POST http://localhost:3001/register
Content-Type : application/json

{
    "name":"jokowi",
    "email":"jokowi@gmail.com",
    "password":"1234"
}

###

POST http://localhost:3001/find
Content-Type : application/json

{
    "email":"jokowi@gmail.com"
}

###
POST http://localhost:3000/auth/register
Content-Type: application/json

{
    "name":"fathoni",
    "email":"fathonizkr@gmail.com",
    "password":"1234"
}

###
POST http://localhost:3000/auth/login
Content-Type: application/json

{
    "email":"fathonizkr@gmail.com",
    "password":"1234"
}

